import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { StrictMode } from 'react';
import 'tailwindcss/tailwind.css';
import { TasksProvider } from '../hooks/TasksProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <StrictMode>
        <TasksProvider>
          <body className={inter.className}>{children}</body>
        </TasksProvider>
      </StrictMode>
      </html>
  )
}
